/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mona.fastcamp;

import java.util.Arrays;
import java.util.List;

import com.mona.fastcamp.logic.BubbleSort;
import com.mona.fastcamp.logic.Sort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Sort<String> logic = new BubbleSort<>();

        List<String> sorted = logic.sort(Arrays.asList(args));

        System.out.println("result=" + sorted);
    }
}
